### ISSUE TITLE
Cannot install Firefox Extension

### ISSUE THREAD

**Issue by gregoryhammond** [keraf/NoCoin#8] opened 2017-09-17 21:07 UTC
I always get the same error when trying to install the firefox extension, I've tried installed it directly from the firefox addons site and downloading the extension and installing it. The error message I get is:

> The addon could not be installed because it appears to be corrupt.

**Comment by keraf** [comment] 2017-09-17 22:02
Thanks for the report. I am currently looking to get ownership of the Add-On as someone else set it up and I will look to get it updated asap.

**Comment by mandx** [comment] 2017-09-18 06:04
Is #11 a duplicate of this?

**Comment by keraf** [comment] 2017-09-18 08:35
@mandx Yes it is, I closed it in favour of this one.

I temporary removed the link to the FF add-on from the readme file and will add it back one this is resolved.

**Comment by keraf** [comment] 2017-09-20 23:55
Little update here: The FF extension failed the submission again but I did fix the findings and submitted it again. Hopefully this time is the good one, fingers crossed!

**Comment by keraf** [comment] 2017-09-21 18:15
Here it is: https://addons.mozilla.org/en-GB/firefox/addon/no-coin/

@gregoryhammond Could you please confirm this is working for you?

**Comment by gregoryhammond** [comment] 2017-09-21 18:33
@keraf I can confirm it works, adds to Firefox (Developer edition) fine and it does work as it says in the readme.

**Comment by keraf** [comment] 2017-09-21 19:15
Awesome! I'll add the link back to the readme and close this is issue.

**Closed by keraf** 2017-09-21 19:15 UTC
Labels: firefox
