### ISSUE TITLE
Coin block not working on most sites

### ISSUE THREAD

**Issue by Piranhazone** [keraf/NoCoin#150] opened 2018-02-03 16:47 UTC
Not sure what it is, I'm not an expert, but I can tell from observing my CPU load, there appears to be a browser miner that NoCoin doesn't block (nor does any other mining blocker I know of).
It's not all that easy to spot, because the websites in question do not always install the hidden miner, so I don't know how I could point you to it, but maybe someone with more insight than me might figure this out.
For all I can tell, one of the sites that most reliably installs this browser miner is
https://wapserv.info/BTC/
and if it doesn't install it, just come back an hour later or so.

**Comment by dehghani-mehdi** [comment] 2018-02-08 08:12
Damn, mentioned link eat my CPU !!
I have installed uBlock Origin and NoCoin.

I also blocked coinhove domains using hosts file (Windows)

**Comment by Piranhazone** [comment] 2018-02-13 19:04
A solution to this would be nice.

**Comment by keraf** [comment] 2018-02-16 00:20
I can only see jsecoin which is already blocked by No Coin. My CPU spikes a bit but it looks to me to be a badly optimised website. Any other inputs before I close this issue?

**Comment by Piranhazone** [comment] 2018-02-16 00:31
Define "a bit".
My I7-7700K goes in turbo mode @ 4.5Ghz and the entire PC is lagging as soon as I open that site.

**Comment by keraf** [comment] 2018-02-16 01:08
Still after a few refreshes, I can't see any mining happening. Anyone else?

No Coin might sometimes not show any detection warning if something else already blocked the ressource (for example adblockers). Can you provide more details? (browser, extensions installed, etc...).

**Comment by Piranhazone** [comment] 2018-02-16 03:59
I have no extensions aside of NoCoin.
I've actually installed a VM with nothing but a plain Win7 and Chrome, just so I can access sites like this one without my whole PC going to stuttering mode.
In this VM, since it's easily reinstalled in case anything goes wrong, I don't even have an Antivirus.

**Comment by Firminator** [comment] 2018-02-20 14:20
I looked into it last week, but couldn't really determine if or if not a miner is active. CPU load was 30% to 40% probably due to background animations. I thought I found an obfuscated script at that time and was about to deobfuscate it but then got sidetracked.

Today I found jsecoin and it was blocked.

**Comment by dehghani-mehdi** [comment] 2018-02-20 15:29
@Firminator I deleted almost any element from HTML (you can try that if you didn't already) and I can say, the CPU usage is not related to background animations or any other regular thing. I tested that in Chrome too.
Also in my friend's PC and same result.

**Comment by keraf** [comment] 2018-02-25 21:31
Without solid reproduction steps or the link to the exact miner script I'm afraid there's not much to do. I'll close this issue and if you happen to find a miner again with reproduction steps, please open a new issue. Cheers!

**Closed by keraf** 2018-02-25 21:31 UTC
Labels: need more info
