### ISSUE TITLE
Free4Faucet.com Miner

### ISSUE THREAD

**Issue by therealmyacorn** [keraf/NoCoin#154] opened 2018-02-09 09:43 UTC
Free4Faucet.com has a hidden miner that is not being blocked... 100% of my CPU is being used...

**Comment by Firminator** [comment] 2018-02-15 15:46
Can't reproduce.

**Comment by keraf** [comment] 2018-02-16 00:08
Created an account and can't see any mining on there. Closing issue.

**Closed by keraf** 2018-02-16 00:08 UTC
