### ISSUE TITLE
can't add to firefox 55

### ISSUE THREAD

**Issue by nurazhar** [keraf/NoCoin#11] opened 2017-09-18 00:00 UTC
![tangkapan skrin 2017-09-18 pada 7 59 31 pg](https://user-images.githubusercontent.com/31495752/30526107-625dac3a-9c47-11e7-8cda-bfdcd990da30.png)

**Comment by keraf** [comment] 2017-09-18 08:34
This is a duplicate of #8 

I temporary removed the link to the FF add-on from the readme file and will add it back one this is resolved.

**Closed by keraf** 2017-09-18 08:34 UTC
Labels: duplicate, firefox
