### ISSUE TITLE
https://tainies.online   blacklist

### ISSUE THREAD

**Issue by blackmouse56** [keraf/NoCoin#169] opened 2018-02-28 12:42 UTC
Hello , first of all thank you for all the work you've done.
The site as u can see in the title " **https://tainies.online** " , the NoCoin in the begining stoped it from using my cpu but at the very next day it just stoped working dont know why or how.
Thank you for your time.

**Comment by Firminator** [comment] 2018-03-01 21:33
Can't reproduce at the moment. If anyone else can reproduce or has more info reply back to this thread.

**Comment by ryanbr** [comment] 2018-03-02 00:17
couple of generics;

https://github.com/easylist/easylist/commit/c880b02f482de4674bfeed60f552fdf9d2eb5e42

`/cryptoloot/*$script`
`/Crypto-Loot/*$script`

**Comment by ryanbr** [comment] 2018-03-02 00:20
github should stop this from happening.

**Comment by blackmouse56** [comment] 2018-03-02 18:43
Tried for like 150+ times today and it blocked the miner every single time , Dunno what happened 2days ago when it wasnt working but now it seems its working just fine. Thank you for your time.

**Comment by keraf** [comment] 2018-03-03 18:21
@blackmouse56 I'll close this issue then :-) If you find any site with a miner that is not blocked by No Coin, feel free to open a new issue. 
@ryanbr I'll add a couple of generics in the next blacklist update, cheers!

**Closed by keraf** 2018-03-03 18:21 UTC
